version: "3.4"

services:
  # mongodb is managed via `run-rs`

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql

  postgre:
    container_name: postgre
    image: postgres:11.7
    ports:
      - 5432:5432
    volumes:
      - postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  mongo_1:
    image: mongo:4.2.3
    ports:
      - 30000:27017
    command: mongod --replSet rs0

  mongo_2:
    image: mongo:4.2.3
    ports:
      - 30001:27017
    command: mongod --replSet rs0

  mongo_3:
    image: mongo:4.2.3
    ports:
      - 30002:27017
    command: mongod --replSet rs0

  init_mongo_rs:
    image: mongo:4.2.3
    depends_on:
      - mongo_1
      - mongo_2
      - mongo_3
    volumes:
      - ./docker/mongo:/scripts
    command: bash /scripts/init-mongo.sh

volumes:
  mysql:
  postgre:
