version: "3.4"

services:
  # add to /etc/hosts `127.0.0.1 mongo_1 mongo_2 mongo_3`

  mongo_1:
    image: mongo:4.2.3
    networks:
      - mongo-cluster
    ports:
      - 30000:30000
    command: mongod --replSet rs0 --port 30000

  mongo_2:
    image: mongo:4.2.3
    networks:
      - mongo-cluster
    ports:
      - 30001:30001
    command: mongod --replSet rs0 --port 30001

  mongo_3:
    image: mongo:4.2.3
    networks:
      - mongo-cluster
    ports:
      - 30002:30002
    command: mongod --replSet rs0 --port 30002

  init_mongo_rs:
    image: mongo:4.2.3
    networks:
      - mongo-cluster
    depends_on:
      - mongo_1
      - mongo_2
      - mongo_3
    volumes:
      - ./docker/mongo:/scripts
    command: bash /scripts/init-mongo.sh

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql

  postgre:
    container_name: postgre
    image: postgres:11.7
    ports:
      - 5432:5432
    volumes:
      - postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  mysql:
  postgre:

networks:
  mongo-cluster:
    driver: bridge
